[project]
name = "lang-chain-learn"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "langchain>=1.4.2",
    "langchain-community>=0.4.2",
    "langchain-deepseek>=1.1.1",
    "langchain-openai>=1.6.4",
    "ollama>=0.6.2",
    "python-dotenv>=1.2.3",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
